### 구글 드라이브 연동

In [91]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### 0. 데이터 불러오기 및 확인

In [92]:
import pandas as pd
onlinesales = pd.read_csv('/content/drive/MyDrive/데이터리안/Data/onlinesales.csv')
customer = pd.read_csv('/content/drive/MyDrive/데이터리안/Data/customer.csv')
titanic_train = pd.read_csv('/content/drive/MyDrive/데이터리안/Data/train.csv')
job = pd.read_csv('/content/drive/MyDrive/데이터리안/Data/job.csv')

In [93]:
onlinesales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52924 entries, 0 to 52923
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    52924 non-null  object
 1   order_id       52924 non-null  object
 2   date           52924 non-null  object
 3   product_id     52924 non-null  object
 4   category       52924 non-null  object
 5   quantity       52924 non-null  int64
 6   avg_cost       52924 non-null  float64
 7   shipping_fee   52924 non-null  float64
 8   coupon_status  52924 non-null  object
dtypes: float64(2), int64(1), object(6)
memory usage: 3.6+ MB

In [94]:
onlinesales.describe()

           quantity      avg_cost  shipping_fee
count  52924.000000  52924.000000  52924.000000
mean       4.497638     52.237646     10.517630
std       20.104711     64.006882     19.475613
min        1.000000      0.390000      0.000000
25%        1.000000      5.700000      6.000000
50%        1.000000     16.990000      6.000000
75%        2.000000    102.130000      6.500000
max      900.000000    355.740000    521.360000

In [95]:
customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1468 entries, 0 to 1467
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  1468 non-null   object
 1   sex          1468 non-null   object
 2   local        1468 non-null   object
 3   period       1468 non-null   int64
dtypes: int64(1), object(3)
memory usage: 46.0+ KB

In [96]:
customer.describe()

            period
count  1468.000000
mean     25.912125
std      13.959667
min       2.000000
25%      14.000000
50%      26.000000
75%      38.000000
max      50.000000

In [97]:
titanic_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [98]:
titanic_train.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [99]:
job.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          100 non-null    int64
 1   job         100 non-null    object
 2   parents_id  100 non-null    int64
dtypes: int64(2), object(1)
memory usage: 2.5+ KB

In [100]:
job.describe()

               id  parents_id
count  100.000000  100.000000
mean   457.850000  114.990000
std    248.578844  221.529281
min      9.000000    0.000000
25%    222.500000    0.000000
50%    488.500000    0.000000
75%    673.000000  128.000000
max    868.000000  868.000000

### 1. 데이터 연결하기2
- LEFT JOIN

In [101]:
titanic_train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [102]:
job.head()

    id          job  parents_id
0  722    developer         714
1   11       police         547
2  818  firefighter         679
3   53      teacher         221
4  139    celebrity         175

In [103]:
# 승객과 관련된 모든 데이터 추출
combined_df = pd.merge(titanic_train, job, left_on = 'PassengerId', right_on = 'id', how = 'left')
combined_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,id,job,parents_id
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,NaN,NaN,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,NaN,NaN,NaN
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,NaN,NaN,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,NaN,NaN,NaN
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,NaN,NaN,NaN

In [104]:
# 직업이 기재되어 있는 사람들만 추출
df_job = combined_df[combined_df['id'].isnull() == False ].reset_index(drop = True)
df_job.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,id,job,parents_id
0,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,9.0,teacher,699.0
1,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S,11.0,police,547.0
2,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C,27.0,celebrity,0.0
3,47,0,3,"Lennon, Mr. Denis",male,NaN,1,0,370371,15.5000,NaN,Q,47.0,celebrity,165.0
4,52,0,3,"Nosworthy, Mr. Richard Cater",male,21.0,0,0,A/4. 39886,7.8000,NaN,S,52.0,police,691.0

In [105]:
# 성인(18세이상)이면서 직업이 기재되어 있는 사람들의 id, Age, job만 추출
df_adult = df_job[df_job['Age'] >= 18].reset_index(drop = True)
df_adult.loc[:4, ['id', 'Age', 'job']]

     id   Age          job
0   9.0  27.0      teacher
1  52.0  21.0       police
2  53.0  49.0      teacher
3  61.0  22.0      teacher
4  91.0  29.0  firefighter

- RIGHT JOIN

In [106]:
# 승객과 관련된 모든 데이터 추출
combined_df1 = pd.merge(job, titanic_train, left_on = 'id', right_on = 'PassengerId', how = 'right')
combined_df1.head()

,id,job,parents_id,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,NaN,NaN,NaN,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,NaN,NaN,NaN,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,NaN,NaN,NaN,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,NaN,NaN,NaN,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,NaN,NaN,NaN,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

- SELF JOIN

In [107]:
# job 테이블에서 자식과 부모가 같은 직업인 경우 확인
job_self_joined = pd.merge(job, job, left_on = 'parents_id', right_on = 'id', how = 'inner').reset_index(drop = True)
job_self_joined.head()

   id_x        job_x  parents_id_x  id_y        job_y  parents_id_y
0   722    developer           714   714       police             0
1    11       police           547   547  firefighter             0
2   818  firefighter           679   679      teacher             0
3    53      teacher           221   221    celebrity             0
4   139    celebrity           175   175    president             0

### 2. 매출 분석

In [108]:
# onlinesales 테이블의 일별 매출액 계산
# sales라는 매출 컬럼 생성
onlinesales['sales'] = onlinesales['quantity'] * onlinesales['avg_cost']

# 일별 매출액 계산
revenue_daily = onlinesales.groupby('date')['sales'].agg('sum').reset_index()
revenue_daily = revenue_daily.rename(columns = {'sales':'revenue_daily'})
revenue_daily.head()

         date  revenue_daily
0  2019-01-01        7380.49
1  2019-01-02       13438.47
2  2019-01-03       23834.21
3  2019-01-04       16603.41
4  2019-01-05       17373.19

In [109]:
# onlinesales 테이블의 일별 매출액, PU, ARPPU 계산
ARPPU = revenue_daily.copy()
ARPPU['PU'] = onlinesales.groupby('date')['customer_id'].agg('nunique').reset_index()['customer_id']
ARPPU

           date  revenue_daily  PU
0    2019-01-01        7380.49   7
1    2019-01-02       13438.47  10
2    2019-01-03       23834.21  14
3    2019-01-04       16603.41   6
4    2019-01-05       17373.19   9
..          ...            ...  ..
360  2019-12-27       13661.59   7
361  2019-12-28       10994.42   5
362  2019-12-29       12011.27   3
363  2019-12-30        8068.47   4
364  2019-12-31       10148.32   6

[365 rows x 3 columns]

In [110]:
ARPPU['ARPPU'] = round(ARPPU['revenue_daily'] / ARPPU['PU'], 2)
ARPPU.head()

         date  revenue_daily  PU    ARPPU
0  2019-01-01        7380.49   7  1054.36
1  2019-01-02       13438.47  10  1343.85
2  2019-01-03       23834.21  14  1702.44
3  2019-01-04       16603.41   6  2767.24
4  2019-01-05       17373.19   9  1930.35

In [111]:
# 일별, 고객별 주문 금액 및 주문수
daily_customer_sales = onlinesales.groupby(['date', 'customer_id']).agg(
    revenue_per_customer = ('sales', 'sum'),
    order_cnts = ('order_id', 'nunique')
).reset_index()

# 결과 확인
daily_customer_sales.head(10)

         date customer_id  revenue_per_customer  order_cnts
0  2019-01-01   USER_0066                821.68           5
1  2019-01-01   USER_0190                933.09           6
2  2019-01-01   USER_0345                  1.24           1
3  2019-01-01   USER_0585                430.19           3
4  2019-01-01   USER_0683                153.71           1
5  2019-01-01   USER_0730                 77.56           1
6  2019-01-01   USER_1358               4963.02          27
7  2019-01-02   USER_0025               1201.65           6
8  2019-01-02   USER_0541                 31.35           1
9  2019-01-02   USER_0585               1847.15          10

In [112]:
# 지역별 1인당 매출액을 순위별로 추출
# 1단계: customer 데이터와 JOIN
local = pd.merge(onlinesales, customer, on = 'customer_id', how = 'inner')

# 2단계: 지역별로 매출, PU 구하기
df_l = local.groupby('local').agg(
    local_revenue = ('sales', 'sum'),
    PU = ('customer_id', 'nunique'),
).reset_index()
df_l

           local  local_revenue   PU
0     California     1442447.31  464
1        Chicago     1625885.58  456
2     New Jersey      409666.86  149
3       New York      937022.63  324
4  Washington DC      255772.24   75

In [113]:
# 3단계: LRPPU(Local Revenue Per Paying User) 계산해서 추가하기
df_l['LRPPU'] = df_l['local_revenue'] / df_l['PU']
df_l.sort_values('LRPPU', ascending = False)

           local  local_revenue   PU        LRPPU
1        Chicago     1625885.58  456  3565.538553
4  Washington DC      255772.24   75  3410.296533
0     California     1442447.31  464  3108.722651
3       New York      937022.63  324  2892.045154
2     New Jersey      409666.86  149  2749.442013

In [114]:
# Chicago 지역에서 제품 카테고리별 주문수, 매출
# 1단계: Chicago 지역 데이터만 따로 추출
df_chicago = local[local['local'] == 'Chicago'].reset_index(drop = True)
df_chicago

,customer_id,order_id,date,product_id,category,quantity,avg_cost,shipping_fee,coupon_status,sales,sex,local,period
0,USER_1358,Transaction_0000,2019-01-01,Product_0981,Nest-USA,1,153.71,6.5,Used,153.71,male,Chicago,12
1,USER_1358,Transaction_0001,2019-01-01,Product_0981,Nest-USA,1,153.71,6.5,Used,153.71,male,Chicago,12
2,USER_1358,Transaction_0002,2019-01-01,Product_0904,Office,1,2.05,6.5,Used,2.05,male,Chicago,12
3,USER_1358,Transaction_0003,2019-01-01,Product_0203,Apparel,5,17.53,6.5,Not Used,87.65,male,Chicago,12
4,USER_1358,Transaction_0003,2019-01-01,Product_0848,Bags,1,16.50,6.5,Used,16.50,male,Chicago,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18375,USER_0167,Transaction_25046,2019-12-31,Product_0981,Nest-USA,1,151.88,6.5,Clicked,151.88,female,Chicago,48
18376,USER_0167,Transaction_25047,2019-12-31,Product_0981,Nest-USA,1,151.88,6.5,Clicked,151.88,female,Chicago,48
18377,USER_0167,Transaction_25048,2019-12-31,Product_0448,Apparel,4,3.47,6.5,Clicked,13.88,female,Chicago,48
18378,USER_0167,Transaction_25048,2019-12-31,Product_0490,Apparel,4,3.47,6.5,Used,13.88,female,Chicago,48
18379,USER_0167,Transaction_25049,2019-12-31,Product_0989,Nest-USA,1,151.88,6.5,Clicked,151.88,female,Chicago,48

In [115]:
# 2단계: 제품 카테고리별 주문수, 매출액 구하기
df_chicago = df_chicago.groupby('category').agg(
    order_cnts = ('order_id', 'nunique'),
    revenue_category = ('sales', 'sum')
).reset_index()
df_chicago.sort_values('revenue_category', ascending = False).reset_index()

    index              category  order_cnts  revenue_category
0      16              Nest-USA        4082         882041.55
1       2               Apparel        2906         214975.27
2      14                  Nest         650         162722.10
3      18                Office        1304          95550.95
4       6             Drinkware         929          76220.24
5       4                  Bags         596          53141.91
6      17  Notebooks & Journals         223          34908.39
7      10              Headgear         238          29982.91
8      15           Nest-Canada         104          24976.27
9      12             Lifestyle         653          23695.81
10      8            Gift Cards          87          10385.14
11      9                Google          33           3464.30
12      3             Backpacks          32           2848.54
13      7                   Fun          52           2660.75
14     19                  Waze         163           2423.94
15      5               Bottles          81           1955.66
16      0           Accessories          68           1879.39
17     11            Housewares          50           1243.40
18     13             More Bags          14            516.74
19      1               Android          18            292.32