### 구글 드라이브 연동

In [70]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### 0. 데이터 불러오기 및 확인

In [71]:
import pandas as pd
titanic_train = pd.read_csv('/content/drive/MyDrive/데이터리안/Data/train.csv')

In [72]:
titanic_train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [73]:
titanic_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [74]:
titanic_train.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

### 1. 숫자 연산

In [75]:
# 더하기(+)
titanic_train['fare_plus10'] = titanic_train['Fare'] + 10
titanic_train.loc[:, ['Fare', 'fare_plus10']]

        Fare  fare_plus10
0     7.2500      17.2500
1    71.2833      81.2833
2     7.9250      17.9250
3    53.1000      63.1000
4     8.0500      18.0500
..       ...          ...
886  13.0000      23.0000
887  30.0000      40.0000
888  23.4500      33.4500
889  30.0000      40.0000
890   7.7500      17.7500

[891 rows x 2 columns]

In [76]:
# 빼기(-)
titanic_train['fare_minus5'] = titanic_train['Fare'] - 5
titanic_train.loc[:, ['Fare', 'fare_minus5']]

        Fare  fare_minus5
0     7.2500       2.2500
1    71.2833      66.2833
2     7.9250       2.9250
3    53.1000      48.1000
4     8.0500       3.0500
..       ...          ...
886  13.0000       8.0000
887  30.0000      25.0000
888  23.4500      18.4500
889  30.0000      25.0000
890   7.7500       2.7500

[891 rows x 2 columns]

In [77]:
# 곱하기 (*)
titanic_train['double_fare'] = titanic_train['Fare'] * 2
titanic_train.loc[:, ['Fare', 'double_fare']]

        Fare  double_fare
0     7.2500      14.5000
1    71.2833     142.5666
2     7.9250      15.8500
3    53.1000     106.2000
4     8.0500      16.1000
..       ...          ...
886  13.0000      26.0000
887  30.0000      60.0000
888  23.4500      46.9000
889  30.0000      60.0000
890   7.7500      15.5000

[891 rows x 2 columns]

In [78]:
# 나누기
titanic_train['fare_divid'] = titanic_train['Fare'] / 2
titanic_train.loc[:, ['Fare', 'fare_divid']]

        Fare  fare_divid
0     7.2500     3.62500
1    71.2833    35.64165
2     7.9250     3.96250
3    53.1000    26.55000
4     8.0500     4.02500
..       ...         ...
886  13.0000     6.50000
887  30.0000    15.00000
888  23.4500    11.72500
889  30.0000    15.00000
890   7.7500     3.87500

[891 rows x 2 columns]

In [118]:
# 나누기(정수만)
titanic_train['fare_divid2'] = titanic_train['Fare'] // 2
titanic_train = titanic_train.astype({'fare_divid2':'int64'})
titanic_train.loc[:, ['Fare', 'fare_divid2']]

        Fare  fare_divid2
0     7.2500            3
1    71.2833           35
2     7.9250            3
3    53.1000           26
4     8.0500            4
..       ...          ...
886  13.0000            6
887  30.0000           15
888  23.4500           11
889  30.0000           15
890   7.7500            3

[891 rows x 2 columns]

In [80]:
# 나머지
titanic_train['fare_divid3'] = titanic_train['Fare'] % 2
titanic_train.loc[:, ['Fare', 'fare_divid3']]

        Fare  fare_divid3
0     7.2500       1.2500
1    71.2833       1.2833
2     7.9250       1.9250
3    53.1000       1.1000
4     8.0500       0.0500
..       ...          ...
886  13.0000       1.0000
887  30.0000       0.0000
888  23.4500       1.4500
889  30.0000       0.0000
890   7.7500       1.7500

[891 rows x 2 columns]

### 2. 연산 함수

In [81]:
# 절대값
titanic_train['fare_abs'] = titanic_train['Fare'].abs()
titanic_train.loc[:, ['Fare', 'fare_abs']]

        Fare  fare_abs
0     7.2500    7.2500
1    71.2833   71.2833
2     7.9250    7.9250
3    53.1000   53.1000
4     8.0500    8.0500
..       ...       ...
886  13.0000   13.0000
887  30.0000   30.0000
888  23.4500   23.4500
889  30.0000   30.0000
890   7.7500    7.7500

[891 rows x 2 columns]

In [82]:
import numpy as np
import math

In [83]:
# 소수점 올림
titanic_train['fare_ceil'] = titanic_train['Fare'].apply(np.ceil)
titanic_train.loc[:, ['Fare', 'fare_ceil']]

        Fare  fare_ceil
0     7.2500        8.0
1    71.2833       72.0
2     7.9250        8.0
3    53.1000       54.0
4     8.0500        9.0
..       ...        ...
886  13.0000       13.0
887  30.0000       30.0
888  23.4500       24.0
889  30.0000       30.0
890   7.7500        8.0

[891 rows x 2 columns]

In [84]:
titanic_train['fare_ceil1'] = np.ceil(titanic_train['Fare'])
titanic_train.loc[:, ['Fare', 'fare_ceil1']]

        Fare  fare_ceil1
0     7.2500         8.0
1    71.2833        72.0
2     7.9250         8.0
3    53.1000        54.0
4     8.0500         9.0
..       ...         ...
886  13.0000        13.0
887  30.0000        30.0
888  23.4500        24.0
889  30.0000        30.0
890   7.7500         8.0

[891 rows x 2 columns]

In [85]:
titanic_train['fare_ceil2'] = titanic_train['Fare'].apply(math.ceil)
titanic_train.loc[:, ['Fare', 'fare_ceil2']]

        Fare  fare_ceil2
0     7.2500           8
1    71.2833          72
2     7.9250           8
3    53.1000          54
4     8.0500           9
..       ...         ...
886  13.0000          13
887  30.0000          30
888  23.4500          24
889  30.0000          30
890   7.7500           8

[891 rows x 2 columns]

In [86]:
# 소수점 내림
titanic_train['fare_floor'] = titanic_train['Fare'].apply(np.floor)
titanic_train.loc[:, ['Fare', 'fare_floor']]

        Fare  fare_floor
0     7.2500         7.0
1    71.2833        71.0
2     7.9250         7.0
3    53.1000        53.0
4     8.0500         8.0
..       ...         ...
886  13.0000        13.0
887  30.0000        30.0
888  23.4500        23.0
889  30.0000        30.0
890   7.7500         7.0

[891 rows x 2 columns]

In [87]:
titanic_train['fare_floor1'] = np.floor(titanic_train['Fare'])
titanic_train.loc[:, ['Fare', 'fare_floor1']]

        Fare  fare_floor1
0     7.2500          7.0
1    71.2833         71.0
2     7.9250          7.0
3    53.1000         53.0
4     8.0500          8.0
..       ...          ...
886  13.0000         13.0
887  30.0000         30.0
888  23.4500         23.0
889  30.0000         30.0
890   7.7500          7.0

[891 rows x 2 columns]

In [88]:
titanic_train['fare_floor2'] = titanic_train['Fare'].apply(math.floor)
titanic_train.loc[:, ['Fare', 'fare_floor2']]

        Fare  fare_floor2
0     7.2500            7
1    71.2833           71
2     7.9250            7
3    53.1000           53
4     8.0500            8
..       ...          ...
886  13.0000           13
887  30.0000           30
888  23.4500           23
889  30.0000           30
890   7.7500            7

[891 rows x 2 columns]

In [89]:
# 반올림
titanic_train['fare_round'] = titanic_train['Fare'].round()
titanic_train.loc[:, ['Fare', 'fare_round']]

        Fare  fare_round
0     7.2500         7.0
1    71.2833        71.0
2     7.9250         8.0
3    53.1000        53.0
4     8.0500         8.0
..       ...         ...
886  13.0000        13.0
887  30.0000        30.0
888  23.4500        23.0
889  30.0000        30.0
890   7.7500         8.0

[891 rows x 2 columns]

In [90]:
titanic_train['fare_round1'] = titanic_train['Fare'].round(1)
titanic_train.loc[:, ['Fare', 'fare_round1']]

        Fare  fare_round1
0     7.2500          7.2
1    71.2833         71.3
2     7.9250          7.9
3    53.1000         53.1
4     8.0500          8.0
..       ...          ...
886  13.0000         13.0
887  30.0000         30.0
888  23.4500         23.4
889  30.0000         30.0
890   7.7500          7.8

[891 rows x 2 columns]

In [91]:
# 거듭제곱
titanic_train['fare_pow'] = titanic_train['Fare'].pow(2)
titanic_train.loc[:, ['Fare', 'fare_pow']]

        Fare     fare_pow
0     7.2500    52.562500
1    71.2833  5081.308859
2     7.9250    62.805625
3    53.1000  2819.610000
4     8.0500    64.802500
..       ...          ...
886  13.0000   169.000000
887  30.0000   900.000000
888  23.4500   549.902500
889  30.0000   900.000000
890   7.7500    60.062500

[891 rows x 2 columns]

In [92]:
titanic_train['fare_pow3'] = titanic_train['Fare'].pow(3)
titanic_train.loc[:, ['Fare', 'fare_pow3']]

        Fare      fare_pow3
0     7.2500     381.078125
1    71.2833  362212.463781
2     7.9250     497.734578
3    53.1000  149721.291000
4     8.0500     521.660125
..       ...            ...
886  13.0000    2197.000000
887  30.0000   27000.000000
888  23.4500   12895.213625
889  30.0000   27000.000000
890   7.7500     465.484375

[891 rows x 2 columns]

In [93]:
titanic_train['fare_rpow'] = titanic_train['Fare'].rpow(2)
titanic_train.loc[:, ['Fare', 'fare_rpow']]

/usr/local/lib/python3.10/dist-packages/pandas/core/nanops.py:1010: RuntimeWarning: overflow encountered in square
  sqr = _ensure_numeric((avg - values) ** 2)

        Fare     fare_rpow
0     7.2500  1.522185e+02
1    71.2833  2.873502e+21
2     7.9250  2.430316e+02
3    53.1000  9.653677e+15
4     8.0500  2.650278e+02
..       ...           ...
886  13.0000  8.192000e+03
887  30.0000  1.073742e+09
888  23.4500  1.145918e+07
889  30.0000  1.073742e+09
890   7.7500  2.152695e+02

[891 rows x 2 columns]

In [94]:
2**71.2833

2.873501908487752e+21

In [95]:
# 제곱근
titanic_train['fare_sqrt'] = np.sqrt(titanic_train['Fare'])
titanic_train.loc[:, ['Fare', 'fare_sqrt']]

        Fare  fare_sqrt
0     7.2500   2.692582
1    71.2833   8.442944
2     7.9250   2.815138
3    53.1000   7.286975
4     8.0500   2.837252
..       ...        ...
886  13.0000   3.605551
887  30.0000   5.477226
888  23.4500   4.842520
889  30.0000   5.477226
890   7.7500   2.783882

[891 rows x 2 columns]

In [96]:
titanic_train['fare_sqrt1'] = titanic_train['Fare'].apply(np.sqrt)
titanic_train.loc[:, ['Fare', 'fare_sqrt1']]

        Fare  fare_sqrt1
0     7.2500    2.692582
1    71.2833    8.442944
2     7.9250    2.815138
3    53.1000    7.286975
4     8.0500    2.837252
..       ...         ...
886  13.0000    3.605551
887  30.0000    5.477226
888  23.4500    4.842520
889  30.0000    5.477226
890   7.7500    2.783882

[891 rows x 2 columns]

In [97]:
titanic_train['fare_sqrt2'] = titanic_train['Fare'].apply(math.sqrt)
titanic_train.loc[:, ['Fare', 'fare_sqrt2']]

        Fare  fare_sqrt2
0     7.2500    2.692582
1    71.2833    8.442944
2     7.9250    2.815138
3    53.1000    7.286975
4     8.0500    2.837252
..       ...         ...
886  13.0000    3.605551
887  30.0000    5.477226
888  23.4500    4.842520
889  30.0000    5.477226
890   7.7500    2.783882

[891 rows x 2 columns]

### 집계 함수

In [98]:
# 개수
titanic_train['Fare'].count()

891

In [99]:
len(titanic_train['Fare'])

891

In [122]:
titanic_train['Fare'].value_counts().sum()

891

In [100]:
# 합계
titanic_train['Fare'].sum()

28693.9493

In [101]:
titanic_train['Fare'].sum().round(0)

28694.0

In [102]:
# 평균
titanic_train['Fare'].mean()

32.204207968574636

In [103]:
# 최소
titanic_train['Age'].min()

0.42

In [104]:
# mysql 결과와 달라 확인해봄
titanic_train[titanic_train['Age'] == 0.42]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,...,fare_floor1,fare_floor2,fare_round,fare_round1,fare_pow,fare_pow3,fare_rpow,fare_sqrt,fare_sqrt1,fare_sqrt2
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,...,8.0,8,9.0,8.5,72.534179,617.751841,366.253821,2.918339,2.918339,2.918339

In [105]:
# 최대
titanic_train['Age'].max()

80.0

### 데이터 요약하기

In [106]:
# groupby
titanic_train.groupby('Sex')['Fare'].mean()

Sex
female    44.479818
male      25.523893
Name: Fare, dtype: float64

In [107]:
titanic_train.groupby(['Sex', 'Pclass'])['Fare'].mean()

Sex     Pclass
female  1         106.125798
        2          21.970121
        3          16.118810
male    1          67.226127
        2          19.741782
        3          12.661633
Name: Fare, dtype: float64

In [108]:
# 조건 추가
group = titanic_train.groupby('Sex')['Fare'].mean()
group[group >= 30]

Sex
female    44.479818
Name: Fare, dtype: float64

In [109]:
# 정렬 추가
titanic_train.groupby(['Sex', 'Pclass'])['Fare'].mean().reset_index().sort_values(by = ['Pclass', 'Sex'])

      Sex  Pclass        Fare
0  female       1  106.125798
3    male       1   67.226127
1  female       2   21.970121
4    male       2   19.741782
2  female       3   16.118810
5    male       3   12.661633

In [110]:
titanic_train.groupby(['Sex', 'Pclass'])['Fare'].mean().reset_index().sort_values(by = ['Pclass', 'Sex'], ascending = [False, True])

      Sex  Pclass        Fare
2  female       3   16.118810
5    male       3   12.661633
1  female       2   21.970121
4    male       2   19.741782
0  female       1  106.125798
3    male       1   67.226127

### 조건문

In [111]:
titanic_train = pd.read_csv('/content/drive/MyDrive/데이터리안/Data/train.csv')

In [112]:
# 조건 1개
titanic_train['age_category'] = np.where(titanic_train['Age'] >= 60, 'old', 'young' )
titanic_train.loc[30:35,['Age', 'age_category']]

     Age age_category
30  40.0        young
31   NaN        young
32   NaN        young
33  66.0          old
34  28.0        young
35  42.0        young

In [113]:
# 조건 2개 이상
filtered = titanic_train[titanic_train['Age'].notna()]

conditions = [
    (filtered['Age'] < 19),
    (filtered['Age'] < 40),
    (filtered['Age'] < 65),
    (filtered['Age'] >= 65),
]

values = ['미성년', '청년', '중장년', '노년']

filtered['age_group'] = np.select(conditions, values)

filtered.loc[24:35,['Age', 'age_group']]

<ipython-input-113-84f8c01f7dc5>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['age_group'] = np.select(conditions, values)

     Age age_group
24   8.0       미성년
25  38.0        청년
27  19.0        청년
30  40.0       중장년
33  66.0        노년
34  28.0        청년
35  42.0       중장년

In [114]:
filtered.groupby(['Sex', 'age_group'])['PassengerId'].count().reset_index().sort_values(by = ['age_group', 'Sex'])

      Sex age_group  PassengerId
3    male        노년           11
0  female       미성년           68
4    male       미성년           71
1  female       중장년           54
5    male       중장년           98
2  female        청년          139
6    male        청년          273